### ISSUE TITLE
Write to a temporary directory rather than user's home directory

### ISSUE THREAD

**Issue by jwokaty** [mengchen18/omicsViewer#2]
I run the builds for Bioconductor and noticed that omicsViewer is writing `temp.db` to the user's home directory on both devel and release, which is not allowed (see [BioC Packages - Other Data](http://contributions.bioconductor.org/data.html#other-data)). We recommend that you use a temporary directory using [BiocFileCache](https://github.com/Bioconductor/BiocFileCache) or R's default caching directory `tools::R_user_dir("omicsViewer", which="cache")`. We appreciate your attention to this matter as well as your contribution to Bioconductor.

**Comment by mengchen18** [comment]
Thanks. The temp file is now saved at ```tools::R_user_dir("omicsViewer", which="cache")```.
